const dictionary = [
    { "a": ["un", "una"] },
    { "abandon": ["abandonar"] },
    { "ability": ["habilidad", "capacidad"] },
    { "able": ["capaz"] },
    { "abortion": ["aborto"] },
    { "about": ["sobre", "acerca de"] },
    { "above": ["encima", "sobre"] },
    { "abroad": ["en el extranjero"] },
    { "absence": ["ausencia"] },
    { "absolute": ["absoluto"] },
    { "absolutely": ["absolutamente"] },
    { "absorb": ["absorber"] },
    { "abuse": ["abuso", "maltrato"] },
    { "academic": ["académico"] },
    { "accept": ["aceptar"] },
    { "access": ["acceso"] },
    { "accident": ["accidente"] },
    { "accompany": ["acompañar"] },
    { "accomplish": ["lograr", "cumplir"] },
    { "according": ["según"] },
    { "account": ["cuenta", "relato"] },
    { "accurate": ["preciso", "exacto"] },
    { "accuse": ["acusar"] },
    { "achieve": ["lograr", "alcanzar"] },
    { "achievement": ["logro", "éxito"] },
    { "acid": ["ácido"] },
    { "acknowledge": ["reconocer", "admitir"] },
    { "acquire": ["adquirir", "obtener"] },
    { "across": ["a través de", "cruzando"] },
    { "act": ["actuar", "acción"] },
    { "action": ["acción"] },
    { "active": ["activo"] },
    { "activist": ["activista"] },
    { "activity": ["actividad"] },
    { "actor": ["actor"] },
    { "actress": ["actriz"] },
    { "actual": ["real", "actual"] },
    { "actually": ["en realidad", "de hecho"] },
    { "ad": ["anuncio", "publicidad"] },
    { "adapt": ["adaptar"] },
    { "add": ["añadir", "agregar"] },
    { "addition": ["adición", "suma"] },
    { "additional": ["adicional"] },
    { "address": ["dirección", "abordar"] },
    { "adequate": ["adecuado"] },
    { "adjust": ["ajustar"] },
    { "adjustment": ["ajuste"] },
    { "administration": ["administración"] },
    { "administrator": ["administrador"] },
    { "admire": ["admirar"] },
    { "admission": ["admisión", "entrada"] },
    { "admit": ["admitir", "confesar"] },
    { "adolescent": ["adolescente"] },
    { "adopt": ["adoptar"] },
    { "adult": ["adulto"] },
    { "advance": ["avanzar", "progresar"] },
    { "advanced": ["avanzado"] },
    { "advantage": ["ventaja", "beneficio"] },
    { "adventure": ["aventura"] },
    { "advertising": ["publicidad", "anuncios"] },
    { "advice": ["consejo", "asesoría"] },
    { "advise": ["aconsejar", "recomendar"] },
    { "adviser": ["asesor", "consejero"] },
    { "advocate": ["defensor", "abogar"] },
    { "affair": ["asunto", "relación"] },
    { "affect": ["afectar", "influenciar"] },
    { "afford": ["permitirse", "costear"] },
    { "afraid": ["temeroso", "asustado"] },
    { "African": ["africano"] },
    { "African-American": ["afroamericano"] },
    { "after": ["después", "tras"] },
    { "afternoon": ["tarde"] },
    { "again": ["otra vez", "de nuevo"] },
    { "against": ["contra", "en contra de"] },
    { "age": ["edad", "época"] },
    { "agency": ["agencia", "organismo"] },
    { "agenda": ["agenda", "orden del día"] },
    { "agent": ["agente", "representante"] },
    { "aggressive": ["agresivo"] },
    { "ago": ["hace (tiempo)"] },
    { "agree": ["estar de acuerdo", "convenir"] },
    { "agreement": ["acuerdo", "contrato"] },
    { "agricultural": ["agrícola"] },
    { "ah": ["ah"] },
    { "ahead": ["adelante", "por delante"] },
    { "aid": ["ayuda", "asistencia"] },
    { "aide": ["ayudante", "asistente"] },
    { "AIDS": ["SIDA"] },
    { "aim": ["objetivo", "apuntar"] },
    { "air": ["aire", "atmósfera"] },
    { "aircraft": ["aeronave", "avión"] },
    { "airline": ["aerolínea"] },
    { "airport": ["aeropuerto"] },
    { "album": ["álbum"] },
    { "alcohol": ["alcohol"] },
    { "alive": ["vivo", "activo"] },
    { "all": ["todo", "todos"] },
    { "alliance": ["alianza"] },
    { "allow": ["permitir", "autorizar"] },
    { "ally": ["aliado", "unirse"] },
    { "almost": ["casi"] },
    { "alone": ["solo", "sola"] },
    { "along": ["a lo largo de", "junto con"] },
    { "already": ["ya"] },
    { "also": ["también"] },
    { "alter": ["alterar", "cambiar"] },
    { "alternative": ["alternativa"] },
    { "although": ["aunque"] },
    { "always": ["siempre"] },
    { "AM": ["AM (antes del mediodía)", "estoy"] },
    { "amazing": ["increíble", "asombroso"] },
    { "American": ["estadounidense", "americano"] },
    { "among": ["entre", "en medio de"] },
    { "amount": ["cantidad", "monto"] },
    { "analysis": ["análisis"] },
    { "analyst": ["analista"] },
    { "analyze": ["analizar"] },
    { "ancient": ["antiguo", "ancestral"] },
    { "and": ["y"] },
    { "anger": ["ira", "enojo"] },
    { "angle": ["ángulo", "perspectiva"] },
    { "angry": ["enojado", "molesto"] },
    { "animal": ["animal"] },
    { "anniversary": ["aniversario"] },
    { "announce": ["anunciar", "proclamar"] },
    { "annual": ["anual"] },
    { "another": ["otro", "otra"] },
    { "answer": ["respuesta", "responder"] },
    { "anticipate": ["anticipar", "prever"] },
    { "anxiety": ["ansiedad", "preocupación"] },
    { "any": ["alguno", "cualquier"] },
    { "anybody": ["alguien", "cualquiera"] },
    { "anymore": ["ya no", "nunca más"] },
    { "anyone": ["cualquiera", "nadie"] },
    { "anything": ["algo", "cualquier cosa"] },
    { "anyway": ["de todas formas", "de todos modos"] },
    { "anywhere": ["en cualquier lugar", "en ningún lugar"] },
    { "apart": ["aparte", "separado"] },
    { "apartment": ["apartamento", "departamento"] },
    { "apparent": ["aparente", "evidente"] },
    { "apparently": ["aparentemente", "al parecer"] },
    { "appeal": ["apelar", "atractivo"] },
    { "appear": ["aparecer", "parecer"] },
    { "appearance": ["apariencia", "aspecto"] },
    { "apple": ["manzana"] },
    { "application": ["aplicación", "solicitud"] },
    { "apply": ["aplicar", "solicitar"] },
    { "appoint": ["nombrar", "designar"] },
    { "appointment": ["cita", "nombramiento"] },
    { "appreciate": ["apreciar", "agradecer"] },
    { "approach": ["enfoque", "aproximarse"] },
    { "appropriate": ["apropiado", "adecuado"] },
    { "approval": ["aprobación", "consentimiento"] },
    { "approve": ["aprobar", "autorizar"] },
    { "approximately": ["aproximadamente", "cerca de"] },
    { "Arab": ["árabe"] },
    { "architect": ["arquitecto", "diseñador"] },
    { "area": ["área", "zona"] },
    { "argue": ["discutir", "argumentar"] },
    { "argument": ["argumento", "discusión"] },
    { "arise": ["surgir", "levantarse"] },
    { "arm": ["brazo", "arma"] },
    { "armed": ["armado"] },
    { "army": ["ejército"] },
    { "around": ["alrededor de", "cerca de"] },
    { "arrange": ["organizar", "disponer"] },
    { "arrangement": ["arreglo", "acuerdo"] },
    { "arrest": ["arrestar", "detener"] },
    { "arrival": ["llegada"] },
    { "arrive": ["llegar"] },
    { "art": ["arte"] },
    { "article": ["artículo", "nota"] },
    { "artist": ["artista"] },
    { "artistic": ["artístico"] },
    { "as": ["como", "mientras que"] },
    { "Asian": ["asiático"] },
    { "aside": ["a un lado", "aparte"] },
    { "ask": ["preguntar", "pedir"] },
    { "asleep": ["dormido"] },
    { "aspect": ["aspecto", "faceta"] },
    { "assault": ["asalto", "agresión"] },
    { "assert": ["afirmar", "reivindicar"] },
    { "assess": ["evaluar", "valorar"] },
    { "assessment": ["evaluación", "valoración"] },
    { "asset": ["activo", "bien"] },
    { "assign": ["asignar", "encomendar"] },
    { "assignment": ["asignación", "tarea"] },
    { "assist": ["asistir", "ayudar"] },
    { "assistance": ["asistencia", "ayuda"] },
    { "assistant": ["asistente", "auxiliar"] },
    { "associate": ["asociar", "relacionar"] },
    { "association": ["asociación", "vinculación"] },
    { "assume": ["asumir", "suponer"] },
    { "assumption": ["suposición", "presunción"] },
    { "assure": ["asegurar", "garantizar"] },
    { "at": ["en", "a"] },
    { "athlete": ["atleta", "deportista"] },
    { "athletic": ["atlético", "deportivo"] },
    { "atmosphere": ["atmósfera", "ambiente"] },
    { "attach": ["adjuntar", "pegar"] },
    { "attack": ["ataque", "atacar"] },
    { "attempt": ["intento", "intentar"] },
    { "attend": ["asistir", "atender"] },
    { "attention": ["atención"] },
    { "attitude": ["actitud", "disposición"] },
    { "attorney": ["abogado", "fiscal"] },
    { "attract": ["atraer"] },
    { "attractive": ["atractivo", "atractiva"] },
    { "attribute": ["atributo", "atribuir"] },
    { "audience": ["audiencia", "público"] },
    { "author": ["autor", "escritor"] },
    { "authority": ["autoridad", "poder"] },
    { "auto": ["automóvil", "auto"] },
    { "available": ["disponible"] },
    { "average": ["promedio", "media"] },
    { "avoid": ["evitar", "eludir"] },
    { "award": ["premio", "galardón"] },
    { "aware": ["consciente", "al tanto"] },
    { "awareness": ["conciencia", "conocimiento"] },
    { "away": ["lejos", "afuera"] },
    { "awful": ["horrible", "terrible"] },
    { "baby": ["bebé", "nene"] },
    { "back": ["espalda", "atrás", "regresar"] },
    { "background": ["fondo", "antecedentes"] },
    { "bad": ["malo", "mala"] },
    { "badly": ["mal", "terriblemente"] },
    { "bag": ["bolsa", "bolso"] },
    { "bake": ["hornear", "cocinar al horno"] },
    { "balance": ["equilibrio", "balance"] },
    { "ball": ["pelota", "bola"] },
    { "ban": ["prohibir", "prohibición"] },
    { "band": ["banda", "grupo musical"] },
    { "bank": ["banco", "orilla"] },
    { "bar": ["barra", "bar"] },
    { "barely": ["apenas", "escasamente"] },
    { "barrel": ["barril", "tambor"] },
    { "barrier": ["barrera", "obstáculo"] },
    { "base": ["base", "fundamento"] },
    { "baseball": ["béisbol"] },
    { "basic": ["básico", "esencial"] },
    { "basically": ["básicamente", "esencialmente"] },
    { "basis": ["base", "fundamento"] },
    { "basket": ["cesta", "canasta"] },
    { "basketball": ["baloncesto", "básquetbol"] },
    { "bathroom": ["baño", "aseo"] },
    { "battery": ["batería", "pila"] },
    { "battle": ["batalla", "lucha"] },
    { "be": ["ser", "estar"] },
    { "beach": ["playa"] },
    { "bean": ["frijol", "haba"] },
];


function populateTable() {
    const tbody = document.querySelector("table tbody");
    tbody.innerHTML = ""; // Limpiar el contenido previo

    dictionary.forEach((entry, index) => {
        const word = Object.keys(entry)[0];
        const translations = entry[word].join(", ");

        const row = document.createElement("tr");

        row.innerHTML = `
            <td>${index + 1}</td>
            <td>${word}</td>
            <td>${translations}</td>
            <td>
                <label for="paperChecks${index + 1}" class="paper-check">
                    <input type="checkbox" name="paperChecks" id="paperChecks${index + 1}" value="option ${index + 1}">
                </label>
            </td>
        `;

        tbody.appendChild(row);
    });
}

// Llamar a la función para llenar la tabla
populateTable();

